version: "3.8"
services:
  db:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: "${mysql_pass}"
    command:
      - "mysqld"
      - "--local_infile=ON"
      # - "--secure_file_priv=''"
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: my_db
        target: /var/lib/mysql
  adminer:
    image: adminer
    container_name: adminer_container
    ports:
      - 8080:8080
volumes:
  my_db: